<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.14.14" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="9.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../AoTomato.Domain/AoTomato.Domain.csproj" />
    <ProjectReference Include="../AoTomato.Repositories/AoTomato.Repositories.csproj" />
    <ProjectReference Include="../AoTomato.Services/AoTomato.Services.csproj" />
  </ItemGroup>

</Project>
